In [1]:
import torch
from torch import nn
from torch.utils.data import DataLoader, Subset
from torchvision import datasets, transforms

torch.manual_seed(42)

transform = transforms.ToTensor()

train_dataset = datasets.FashionMNIST(
    root="./data",
    train=True,
    transform=transform,
    download=True
)

In [2]:
indices = torch.randperm(len(train_dataset))[:64]
small_dataset = Subset(train_dataset, indices)

small_loader = DataLoader(
    small_dataset,
    batch_size=64,
    shuffle=True
)

In [3]:
x, y = next(iter(small_loader))

print(x.shape)
print(y.shape)
print(y)
print(torch.bincount(y, minlength=10))

torch.Size([64, 1, 28, 28])
torch.Size([64])
tensor([7, 2, 6, 6, 6, 6, 9, 5, 6, 5, 7, 2, 5, 8, 5, 4, 8, 4, 0, 0, 7, 9, 5, 2,
        8, 7, 9, 4, 7, 7, 7, 9, 4, 6, 7, 2, 4, 5, 9, 3, 1, 9, 2, 1, 4, 7, 1, 2,
        6, 7, 7, 1, 5, 6, 2, 1, 1, 0, 1, 0, 0, 6, 0, 0])
tensor([ 7,  7,  7,  1,  6,  7,  9, 11,  3,  6])


In [5]:
model = nn.Sequential(
    nn.Flatten(),
    nn.Linear(28*28,256),
    nn.ReLU(),
    nn.Linear(256,10)
)

In [6]:
logits = model(x)

print(logits.shape)
print(logits[0])

torch.Size([64, 10])
tensor([ 0.0388, -0.0149,  0.0271,  0.0388, -0.0646,  0.0888,  0.0447, -0.1547,
         0.0091,  0.1071], grad_fn=<SelectBackward0>)


In [8]:
predictions = logits.argmax(dim=1)
accuracy = (predictions == y).float().mean().item()
print("训练前准确率：", accuracy)

训练前准确率： 0.109375


In [9]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001
)

In [10]:
for epoch in range(300):
    model.train()

    for x,y in small_loader:
        logits = model(x)
        loss = loss_fn(logits,y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    if (epoch + 1) % 20 == 0:
        model.eval()

        with torch.no_grad():
            logits = model(x)
            predictions = logits.argmax(dim=1)
            accuracy = (predictions == y).float().mean().item()

        print(
            f"epoch={epoch + 1:3d}, "
            f"loss={loss.item():.4f}, "
            f"accuracy={accuracy:.4f}"
        )

epoch= 20, loss=0.5466, accuracy=0.9375
epoch= 40, loss=0.1002, accuracy=1.0000
epoch= 60, loss=0.0247, accuracy=1.0000
epoch= 80, loss=0.0115, accuracy=1.0000
epoch=100, loss=0.0074, accuracy=1.0000
epoch=120, loss=0.0053, accuracy=1.0000
epoch=140, loss=0.0041, accuracy=1.0000
epoch=160, loss=0.0033, accuracy=1.0000
epoch=180, loss=0.0027, accuracy=1.0000
epoch=200, loss=0.0023, accuracy=1.0000
epoch=220, loss=0.0019, accuracy=1.0000
epoch=240, loss=0.0016, accuracy=1.0000
epoch=260, loss=0.0014, accuracy=1.0000
epoch=280, loss=0.0013, accuracy=1.0000
epoch=300, loss=0.0011, accuracy=1.0000


In [11]:
model = nn.Sequential(
    nn.Flatten(),
    nn.Linear(28 * 28, 16),
    nn.ReLU(),
    nn.Linear(16, 10)
)

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001
)

In [12]:
for epoch in range(300):
    model.train()

    for x,y in small_loader:
        logits = model(x)
        loss = loss_fn(logits,y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    if (epoch + 1) % 20 == 0:
        model.eval()

        with torch.no_grad():
            logits = model(x)
            predictions = logits.argmax(dim=1)
            accuracy = (predictions == y).float().mean().item()

        print(
            f"epoch={epoch + 1:3d}, "
            f"loss={loss.item():.4f}, "
            f"accuracy={accuracy:.4f}"
        )

epoch= 20, loss=1.5820, accuracy=0.5625
epoch= 40, loss=1.0731, accuracy=0.6875
epoch= 60, loss=0.7432, accuracy=0.9062
epoch= 80, loss=0.5181, accuracy=0.9375
epoch=100, loss=0.3596, accuracy=0.9531
epoch=120, loss=0.2504, accuracy=0.9844
epoch=140, loss=0.1768, accuracy=1.0000
epoch=160, loss=0.1274, accuracy=1.0000
epoch=180, loss=0.0941, accuracy=1.0000
epoch=200, loss=0.0714, accuracy=1.0000
epoch=220, loss=0.0556, accuracy=1.0000
epoch=240, loss=0.0442, accuracy=1.0000
epoch=260, loss=0.0359, accuracy=1.0000
epoch=280, loss=0.0297, accuracy=1.0000
epoch=300, loss=0.0249, accuracy=1.0000
